apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ebis92vfl-java-quarkus 
  janus-idp.io/tekton: ebis92vfl-java-quarkus
  backstage.io/kubernetes-id: ebis92vfl-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ebis92vfl-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml